### ISSUE TITLE
How to use.

### ISSUE THREAD

**Issue by potatochipsnotincluded** [kosmotema/sdl2-nuget#25]
I've tried `using SDL2` and `using SDL`. I can't figure out

**Comment by cylixlee** [comment]
Me too.. I tried installing all packages of SDL from nuget (image, ttf, etc) but there's no `SDL` namespace thing. @kosmotema any demo or doc to explain usage?

**Comment by kasmacioma** [comment]
Hello. It looks like you're trying to use this package in a C# project, but `sdl2.nuget` is only for C++ projects.

So you need another package like [Ryujinx.SDL2-CS](https://www.nuget.org/packages/Ryujinx.SDL2-CS) or [ppy.SDL2-CS](https://www.nuget.org/packages/ppy.SDL2-CS) (or any other `SDL2 bindings for C#` package)

**Comment by potatochipsnotincluded** [comment]
Please clarify this in the documentation.
